create table if not exists public.virtual_notes (
  id bigint generated by default as identity primary key,
  owner_id uuid,
  title text not null,
  content text not null,
  created_at timestamptz not null default now()
);

alter table public.virtual_notes enable row level security;

revoke all on table public.virtual_notes from anon;
revoke all on table public.virtual_notes from authenticated;

insert into public.virtual_notes (owner_id, title, content)
select
  null,
  note.title,
  note.content
from (
  values
    ('과제', '실습용 가상 과제 기록'),
    ('포트폴리오', '실습용 가상 포트폴리오 기록'),
    ('아침 리추얼', '실습용 가상 리추얼 기록'),
    ('훈련 행정 자료', '실습용 가상 행정 기록')
) as note(title, content)
where not exists (
  select 1
  from public.virtual_notes existing
  where existing.title = note.title
    and existing.content = note.content
);
